name: Bug Report
description: File a bug report
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for using GalaxySlicer and wanting to report a bug.**
        Before filing, please check if the issue already exists (either open or closed) by using the search bar on the issues page. If it does, comment there. Even if it's closed, we can reopen it based on your comment.
  - type: input
    id: version
    attributes:
      label: GalaxySlicer Version
      description: Which version of GalaxySlicer are you running? You can see the full version in `Help` -> `About GalaxySlicer`.
      placeholder: e.g. V1.0.0-alpha
      validations:
      required: true
  - type: dropdown
    id: os_info
    attributes:
      label: OS version
      description: Which OS version are you using?
      multiple: false
      options:
        - macOS 12
        - macOS 13
        - macOS 14
        - Windows 10
        - Windows 11
    validations:
      required: true
  - type: dropdown
    id: os_arch
    attributes:
      label: OS architecture
      description: Which OS architecture are you using?
      multiple: false
      options:
        - x64
        - arm64
      default: 0
    validations:
      required: true
  - type: textarea
    id: system_info
    attributes:
      label: Additional system information
      description: For the performance issue, please also show the CPU、Memory information; For the 3D Rendering issue, please also show the Display Card information.
      placeholder: |
        CPU: 11th gen intel r core tm i7-1185g7/amd ryzen 7 6800h/...
        Memory: 32/16 GB...
        Display Card: NVIDIA Quadro P400/...
    validations:
      required: false
  - type: input
    id: printer
    attributes:
      label: Printer
      description: Which printer was selected
      placeholder: Bambu Lab X1 series/Bambu Lab P1P/...
    validations:
      required: true
  - type: textarea
    id: reproduce_steps
    attributes:
      label: How to reproduce
      description: Please described the detailed steps to reproduce this issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: actual_results
    attributes:
      label: Actual results
      description: What happens after the above steps? Please, enclose a screenshot whenever possible (even when you think the description is clear). 
    validations:
      required: true
  - type: textarea
    id: expected_results
    attributes:
      label: Expected results
      description: What should happen after the above steps?
      validations:
      required: true
  - type: markdown
    id: file_required
    attributes:
      value: |
        Please be sure to add the following files:
          * Please upload a ZIP archive containing the **project file** used when the problem arise. Please export it just before or after the problem occurs. Even if you did nothing and/or there is no object, export it! (We need the configurations in project file).
            You can export the project file from the application menu in `File`->`Save project as...`, then zip it
          * A **log file** for crashes and similar issues.
            You can find your log file here:
            Windows: `%APPDATA%\GalaxySlicer\log` or usually `C:\Users\<your username>\AppData\Roaming\GalaxySlicer\log`
            MacOS: `$HOME/Library/Application Support/GalaxySlicer/log`
            Linux: `$HOME/.config/GalaxySlicer/log`
            If Bambu Studio still starts, you can also reach this directory from the application menu in `Help` -> `Show Configuration Folder`
            You can zip the log directory, or just select the newest logs when this issue happens, and zip them
  - type: textarea
    id: file_uploads
    attributes:
      label: Project file & Debug log uploads
      description:  Drop the project file and debug log here
      placeholder: |
        Project File: `File` -> `Save project as...` then zip it & drop it here
        Log File:  `Help` -> `Show Configuration Folder`, then zip the log directory, or just select the newest logs in `log` when this issue happens and zip them, then drop the zip file here
    validations:
      required: true
  - type: checkboxes
    id: file_checklist
    attributes:
      label: Checklist of files to include
      options:
        - label: Log file
        - label: Project file
