name: Custom issue template
description: For generic ideas such as enhancement of a feature, some questions, and etc.
body:
- type: input
  id: version
  attributes:
    label: GalaxySlicer Version
    description: Which version of GalaxySlicer are you running? You can see the full version in `Help` -> `About GalaxySlicer`.
    placeholder: e.g. V1.0.0-alpha
  validations:
    required: true
