name: Build all

on:
  push:
    branches:
      - master
      - release/*
    paths:
      - 'deps/**'
      - 'src/**'
      - '**/CMakeLists.txt'
      - 'version.inc'
      - 'localization/**'
      - 'resources/**'
      - ".github/workflows/build_*.yml"
  pull_request:
    branches:
      - master
      - release/*
    paths:
      - 'deps/**'
      - 'src/**'
      - '**/CMakeLists.txt'
      - 'version.inc'
      - ".github/workflows/build_*.yml"
  workflow_dispatch:
    inputs:
      build-deps-only:
        description: 'Only build dependencies (bypasses caching)'
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_all:
    name: Build All
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
          - os: windows-latest
          - os: macos-12
            arch: x86_64
          - os: macos-12
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dev on Windows
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.1

      - name: Get the date on Ubuntu and macOS
        if: matrix.os != 'windows-latest'
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      - name: Get the date on Windows
        if: matrix.os == 'windows-latest'
        run: echo "date=$(Get-Date -Format 'yyyyMMdd')" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
        shell: pwsh

      # Specific build steps for each OS
      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        run: |
            choco install strawberryperl
            mkdir deps/build
            mkdir deps/build/OrcaSlicer_dep
            .\build_release_vs2022.bat deps
            .\build_release_vs2022.bat pack

      - name: Build on Mac ${{ matrix.arch }}
        if: matrix.os == 'macos-12'
        run: |
            brew install cmake git gettext automake texinfo
            mkdir -p deps/build_${{ matrix.arch }}/OrcaSlicer_dep_${{ matrix.arch }}
            ./build_release_macos.sh -dp -a ${{ matrix.arch }} -t 10.15

      - name: Build on Ubuntu
        if: matrix.os == 'ubuntu-20.04'
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake git
            mkdir -p deps/build/destdir
            ./BuildLinux.sh -dr

      - name: Invoke Reusable Workflow
        uses: ./.github/workflows/build_check_cache.yml@master
        with:
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
          build-deps-only: ${{ github.event.inputs.build-deps-only || false }}
