name: Build AppImage x64

on:
  push:
    branches:
      - main
      - master
      - release/*
    paths:
      - 'deps/**'
      - 'src/**'
      - '**/CMakeLists.txt'
      - 'version.inc'
      - 'localization/**'
      - 'resources/**'
      - 'bbl/**'
      - ".github/workflows/build_*.yml"
      
  pull_request:
    branches:
      - main
      - master
      - release/*
    paths:
      - 'deps/**'
      - 'src/**'
      - '**/CMakeLists.txt'
      - 'version.inc'
      - 'localization/**'
      - 'resources/**'
      - 'bbl/**'
      - ".github/workflows/build_*.yml"
      
  workflow_dispatch:
    inputs:
      build-deps-only:
        description: 'Only build dependencies (bypasses caching)'
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:

  build_linux_appimage:
    name: Build Linux AppImage
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
            
      - name: Prepare the system
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y cmake git build-essential libunwind-dev libgstreamer1.0-dev

      - name: Install additional dependencies
        run: |
          sudo apt-get install -y libgl1-mesa-dev libxkbcommon-dev wayland-protocols extra-cmake-modules pkgconf libgtk-3-dev libsoup2.4-dev libwebkit2gtk-4.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev gstreamer1.0-plugins-bad

      - name: Fix and clean up broken installations
        run: |
          sudo apt-get -f install
          sudo apt-get autoremove

      - name: Build on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake git
            mkdir -p deps/build/destdir
            sudo bash ./BuildLinux.sh -u
            sudo bash ./BuildLinux.sh -d
            sudo bash ./BuildLinux.sh -i            
        
      - name: Upload AppImage Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: AppImage
          path: ${{ github.workspace }}/deps/build/destdir
